apiVersion: v2
description: PaymentHub EE Barebone Edition
type: application
name: ph-ee-g2psandbox
version: 1.1.0
appVersion: 1.1.0

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine/ph-ee-engine-1.9.0-SNAPSHOT.tgz
  version: 1.9.0-SNAPSHOT
